name: Build

on:
  workflow_dispatch:
  push:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
  schedule:
    - cron: '0 6 * * 0'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        
      - name: Setup pnpm
        uses: pnpm/action-setup@fe02b34f77f8bc703788d5817da081398fad5dd2
        # Pinned to commit hash of release v4.0.0 on 05/07/24.
        
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install
  
      - name: Lint
        run: pnpm lint

      - name: Unit Test
        run: pnpm test:unit

      - name: Build
        run: pnpm build
