name: Node.js CI

on:
  push:
  pull_request:
    types: [assigned, opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 22.x

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "dir=$(yarn cache dir)" >> $GITHUB_OUTPUT

      - name: Cache yarn and next
        uses: actions/cache@v4
        with:
          path: |
            ${{ steps.yarn-cache-dir-path.outputs.dir }}
            ${{ github.workspace }}/.next/cache
          # Generate a new cache whenever packages or source files change.
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/yarn.lock') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
          # If source files changed but packages didn't, rebuild from a prior cache.
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/yarn.lock') }}-

      - name: Install dependencies
        run: yarn install

      - name: Install Playwrigtht dependencies
        run: yarn playwright install --with-deps

      - name: Lint, build, and test Socialify
        run: yarn verify
        env:
          # GITHUB_TOKEN is a reserved env, use step-level rewrite to
          # replace with Socialify's repo-scoped GITHUB_TOKEN env.
          GITHUB_TOKEN: ${{ secrets.SOCIALIFY_GITHUB_TOKEN }}
          PROJECT_URL: ${{ secrets.SOCIALIFY_PROJECT_URL }}
          